USE [master]
GO

/****** Object:  Database [Recipes]    Script Date: 25.01.2018 11:38:59 ******/
CREATE DATABASE [Recipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Recipes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Recipes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Recipes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Recipes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Recipes] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Recipes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Recipes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Recipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Recipes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Recipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Recipes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Recipes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Recipes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Recipes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Recipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Recipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Recipes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Recipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Recipes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Recipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Recipes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Recipes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Recipes] SET  MULTI_USER 
GO

ALTER DATABASE [Recipes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Recipes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Recipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Recipes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Recipes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Recipes] SET QUERY_STORE = OFF
GO

USE [Recipes]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Recipes] SET  READ_WRITE 
GO

